name: Staging Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: SSH key generate
        run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Rsync deploy
        run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 10022" --delete ./* xs875751@sv13219.xserver.jp:/home/xs875751/shuuu.jp/public_html/test/works/relationship-model --exclude .htaccess
